INSERT INTO
  `careers` (`career_name`)
VALUES
  ('ADMINISTRACIÓN DE RECURSOS HUMANOS'),
  ('COMPONENTE BASICO Y PROPEDEUTICO'),
  ('CONTABILIDAD'),
  ('ELECTRICIDAD'),
  ('OFIMÁTICA'),
  ('PROGRAMACIÓN'),
  ('SOPORTE Y MANTENIMIENTO DE EQUIPO DE CÓMPUTO'),
  ('TRABAJO SOCIAL');