INSERT INTO
  `subjects` (`subject_name`)
VALUES
  (
    'APLICA EL MÉTODO DE PROMOCIÓN SOCIAL COMUNITARIO'
  ),
  (
    'APLICA LA METODOLOGÍA DE DESARROLLO RÁPIDO DE APLICACIONES CON PROGRAMACIÓN ORIENTADA A EVENTOS'
  ),
  (
    'APLICA LA METODOLOGÍA ESPIRAL CON PROGRAMACIÓN ORIENTADA A OBJETOS'
  ),
  ('BIOLOGÍA'),
  ('CÁLCULO INTEGRAL'),
  ('CIENCIA, TECNOLOGÍA, SOCIEDAD Y VALORES'),
  ('CIENCIAS SOCIALES I'),
  ('CLASIFICA LOS ELEMENTOS BÁSICOS DE LA RED LAN'),
  ('CONSTRUYE BASES DE DATOS PARA APLICACIONES WEB'),
  (
    'CONTRIBUYE A LA INTEGRACIÓN Y DESARROLLO DEL PERSONAL EN LA ORGANIZACIÓN'
  ),
  ('CULTURA DIGITAL I'),
  (
    'DESARROLLA APLICACIONES WEB CON CONEXIÓN A BASES DE DATOS'
  ),
  ('DISEÑA BASES DE DATOS OFIMÁTICAS'),
  ('DISEÑA LA RED LAN'),
  (
    'DISEÑA MATERIAL DIDÁCTICO PARA LA ORIENTACIÓN SOCIAL'
  ),
  ('DISEÑA Y MANTIENE LOS SISTEMAS DE ILUMINACIÓN'),
  ('ELABORA PROYECTOS DE ORIENTACIÓN SOCIAL'),
  ('ÉTICA'),
  ('FÍSICA II'),
  (
    'GENERA INFORMACIÓN FISCAL DE LAS PERSONAS FÍSICAS'
  ),
  (
    'GENERA INFORMACIÓN FISCAL DE LAS PERSONAS MORALES'
  ),
  ('GEOMETRÍA ANALÍTICA'),
  (
    'GESTIONA INFORMACIÓN MEDIANTE EL USO DE HOJAS DE CÁLCULO'
  ),
  (
    'GESTIONA INFORMACIÓN MEDIANTE EL USO DE PROCESADORES DE TEXTO'
  ),
  (
    'GESTIONA INFORMACIÓN MEDIANTE EL USO DE SISTEMAS MANEJADORES DE BASES DE DATOS OFIMÁTICAS'
  ),
  (
    'GESTIONA INFORMACIÓN MEDIANTE EL USO DE SOFTWARE DE PRESENTACIONES'
  ),
  ('HUMANIDADES I'),
  (
    'IMPLEMENTA Y MANTIENE LOS SISTEMAS DE ENERGÍA RENOVABLE'
  ),
  ('INGLÉS I'),
  ('INGLÉS III'),
  ('INGLÉS V'),
  ('LA MATERIA Y SUS INTERACCIONES'),
  ('LENGUA Y COMUNICACIÓN I'),
  ('MANTIENE LOS GENERADORES DE CA Y CC'),
  ('MANTIENE LOS MOTORES DE CA Y CC'),
  (
    'MÓDULO II. APLICA METODOLOGÍAS DE DESARROLLO DE SOFTWARE CON HERRAMIENTAS DE PROGRAMACIÓN VISUAL'
  ),
  ('MÓDULO II. GESTIONA INFORMACIÓN DE MANERA LOCAL'),
  (
    'MÓDULO II. INTEGRA EL CAPITAL HUMANO A LA ORGANIZACIÓN'
  ),
  (
    'MÓDULO II. MANTIENE HARDWARE Y SOFTWARE EN EL EQUIPO DE CÓMPUTO'
  ),
  (
    'MÓDULO II. MANTIENE LOS MOTORES Y GENERADORES DE CA Y CC'
  ),
  (
    'MÓDULO II. OPERA LOS PROCESOS CONTABLES DENTRO DE UN SISTEMA ELECTRÓNICO'
  ),
  (
    'MÓDULO II. PROMUEVE EN LA COMUNIDAD SERVICIOS Y PROGRAMAS INSTITUCIONALES'
  ),
  ('MÓDULO IV. APOYA EN LA ATENCIÓN INDIVIDUALIZADA'),
  (
    'MÓDULO IV. CONTROLA LOS PROCESOS Y SERVICIOS DE HIGIENE Y SEGURIDAD DEL CAPITAL HUMANO EN LA ORGANIZACIÓN'
  ),
  (
    'MÓDULO IV. DESARROLLA SOFTWARE DE APLICACIÓN WEB CON ALMACENAMIENTO PERSISTENTE DE DATOS'
  ),
  (
    'MÓDULO IV. DETERMINA LAS CONTRIBUCIONES FISCALES DE PERSONAS FÍSICAS Y MORALES'
  ),
  ('MÓDULO IV. DISEÑA REDES DE COMPUTADORAS'),
  (
    'MÓDULO IV. DISEÑA Y GESTIONA BASES DE DATOS OFIMÁTICAS'
  ),
  (
    'MÓDULO IV. DISEÑA Y MANTIENE LOS SISTEMAS DE ILUMINACIÓN Y DE ENERGÍA RENOVABLE'
  ),
  (
    'ORIENTA AL INDIVIDUO Y LO VINCULA A REDES SOCIALES DE APOYO PARA LA ATENCIÓN INDIVIDUALIZADA'
  ),
  ('PENSAMIENTO MATEMÁTICO I'),
  (
    'REALIZA EL ESTUDIO SOCIAL PARA LA ATENCIÓN INDIVIDUALIZADA'
  ),
  ('REALIZA EL PROCESO DE ADMISIÓN Y EMPLEO'),
  (
    'REALIZA MANTENIMIENTO A LAS INSTALACIONES ELÉCTRICAS RESIDENCIALES, COMERCIALES E INDUSTRIALES'
  ),
  ('REALIZA MANTENIMIENTO CORRECTIVO'),
  ('REALIZA MANTENIMIENTO PREVENTIVO'),
  ('RECURSOS SOCIOEMOCIONALES I'),
  (
    'REGISTRA INFORMACIÓN CONTABLE EN FORMA ELECTRÓNICA'
  ),
  (
    'REGISTRA INFORMACIÓN DE LOS RECURSOS FINANCIEROS'
  ),
  ('REGISTRA INFORMACIÓN DE LOS RECURSOS MATERIALES'),
  (
    'SUPERVISA EL CUMPLIMIENTO DE LAS MEDIDAS DE HIGIENE Y SEGURIDAD EN LA ORGANIZACIÓN'
  ),
  (
    'SUPERVISA EL CUMPLIMIENTO DE TAREAS Y PROCESOS PARA EVALUAR LA PRODUCTIVIDAD EN LA ORGANIZACIÓN'
  );